version: '3.3'

services:
   dacs2019walter:
     depends_on:
       - dbjon  
     image: dacs2019jon:latest
     ports:
       - "8050:8080"
     restart: always
     environment:
       - SPRING_PROFILES_ACTIVE=prod
       - DACS2019_DB_HOST=jdbc:mysql://localhost:3306/bookstore?useTimezone=true&serverTimezone=UTC
       - DACS2019_DB_USERNAME=jon
       - DACS2019_DB_PASSWORD=jonjon
   dbwalter:
     image: mysql:5.7
     restart: always
#     ports:
#       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: univille
       MYSQL_DATABASE: bookstore
       MYSQL_USER: jon
       MYSQL_PASSWORD: jonjon